---
name: ♻️ Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@72a6b41dd6f2ccce15aa70b0e42178f6f5583018 # v5.3.0
    with:
      super-linter-variables: |
        {
          "VALIDATE_CSS": false,
          "VALIDATE_CSS_PRETTIER": false,
          "VALIDATE_EDITORCONFIG": false,
          "VALIDATE_HTML": false,
          "VALIDATE_HTML_PRETTIER": false,
          "VALIDATE_JAVASCRIPT_ES": false,
          "VALIDATE_JAVASCRIPT_PRETTIER": false,
          "VALIDATE_JSCPD": false,
          "VALIDATE_MARKDOWN": false,
          "VALIDATE_MARKDOWN_PRETTIER": false,
          "VALIDATE_PYTHON_BLACK": false,
          "VALIDATE_PYTHON_PYLINT": false,
          "VALIDATE_PYTHON_FLAKE8": false,
          "VALIDATE_PYTHON_ISORT": false,
          "VALIDATE_PYTHON_MYPY": false,
          "VALIDATE_PYTHON_RUFF": false,
          "VALIDATE_YAML": false
        }
